# Generated by Django 5.2.4 on 2025-08-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
