# Generated by Django 5.2.4 on 2025-08-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_registration_queue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='artpiece',
            options={'ordering': ['title', 'artist__name']},
        ),
        migrations.AlterModelOptions(
            name='clerk',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['-start_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='exhibitionartpiece',
            options={'ordering': ['exhibition', 'art_piece']},
        ),
        migrations.AlterModelOptions(
            name='setupstatus',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['name']},
        ),
    ]
